### ISSUE TITLE
Error loading builder_embed_css with pip installed escher

### ISSUE THREAD

**Issue by pstjohn** [zakandrewking/escher#109]
pip-installing escher results in the first line of `version.py` reading:

```
__version__ = '1.1.2.post1' 
```

This causes the `b.display_in_notebook(js_source='web')` (from `COBRApy and Escher.ipynb`) to fail with the error `'Could not find builder_embed_css.'`

Its being caused by the fact that the css url is auto-generated from the version string, and `https://escher.github.io/builder-embed-1.1.2.post1.css` doesn't exist on the escher website.

Changing it back to the github version '1.1.2' fixes the issue, but worth noting that the python examples will fail with a pip installed package.

**Comment by zakandrewking** [comment]
Thanks for submitting this. PyPI requires those post-release versions, and I pushed the version without thinking it through completely.

It should be fixed with v1.1.2.post2. Please let me know if it works for you.

**Comment by pstjohn** [comment]
Can confirm the post2 upload works fine out-of-the-box.

Thanks for the great package and the quick response!
