### ISSUE TITLE
Download json map doesn't work

### ISSUE THREAD

**Issue by joaocardoso** [zakandrewking/escher#119]
Hi Zak,

I cannot download a map I edited.
It opens a new window and then nothing.
There is an error in my webkit console:

 [Error] Failed to load resource: Frame load interrupted (blob:http://escher.github.io/76237aba-746e-4ce5-a98d-80174dddd8c1, line 0)

**Comment by zakandrewking** [comment]
This might be fixed by #120, which will be v1.2.1

**Comment by zakandrewking** [comment]
Let me know if this is fixed.

**Comment by joaocardoso** [comment]
Yes, it's fixed! Thanks
