### ISSUE TITLE
Python API: save_html

### ISSUE THREAD

**Issue by JuBra** [zakandrewking/escher#132]
Hello,
the save_html functions seems to be broken.
Using js_source="web" the protocol part is missing in the link to the js files in theresulting html file which leads to an error while loading in both firefox and chrome.

Using js_source="local" results in ValueError: unknown url type: 'escher/css/builder-embed-1.3.1.css'.

A snippet reproducing the error message:

import escher

modelMap = escher.Builder(map_name="iJO1366.Central metabolism.json")
modelMap.save_html("test.html", js_source="local")

**Comment by zakandrewking** [comment]
Leaving off the protocol was done on purpose. This allows the HTML file to be agnostic of http vs. https. However, if you open an HTML file in the browser as a file, then it won't work.

There are two solutions:

**Short term**:  You can use a local web server to look at your HTML files. For instance, if you have Python installed, you can start a server on port 8000 with this command:

```
python -m SimpleHTTPServer 8000
```

The site will be available at http://localhost:8000/test.html

**Medium term**:  I can add an option to save_html that adds the protocols so users can open the HTML as a file.

In both cases, continue using js_source="web".

**Comment by JuBra** [comment]
Thank you for the clarification.
However, coming back to the options for the source of the js files, I would prefer using the local version of the files as I am not always connected to the internet. Would it be too much to ask to fix this option as well? Otherwise I would also be happy to track down the error and fix it myself.

**Comment by zakandrewking** [comment]
I will keep this issue open and add that fix for save_html. I think it makes sense.

However, the local web server _will_ work offline. Using a local web server is generally a more robust way to deal with local HTML files. There is a nice discussion on MDN:

https://developer.mozilla.org/en-US/Learn/Open_a_file_in_a_browser

As a side note, here are some other alternatives to the python server that I mentioned above:

http://stackoverflow.com/questions/12905426/what-is-a-faster-alternative-to-pythons-simplehttpserver

**Comment by zakandrewking** [comment]
OK. Version 1.4 (coming soon) will fix this. When js_source is 'web', the https protocol will be used by default and a new protocol keyword argument lets you change this. When js_source is 'local', escher saves all the dependencies for the map into a folder that works offline. Both options should work without a web server.

**Comment by JuBra** [comment]
Thank you for the fix!
