### ISSUE TITLE
save map 

### ISSUE THREAD

**Issue by alyamahmoud** [zakandrewking/escher#135]
Hi Zachary

I am trying to save a map in Escher that I have been editing online (through the builder) but whenever I press the save map JSON, I am prompted to the page source I guess blob:https://escher.github.io/ce2495c6-6751-4ea0-b2e2-a06d994c3894 

previously (till fews days ago), it would automatically download a zipped file with the map. 

Same goes for exporting the map as .svg, now it just opens the sag file in a browser but doesn't save the file. 

My question is: how do I save the map file i have been working on so that I can continue to edit in escher ?

Thanks a lot
Alyaa

**Comment by zakandrewking** [comment]
Are you using Safari?




Best

Zak

**Comment by alyamahmoud** [comment]
yes

**Comment by alyamahmoud** [comment]
Any chance I can save the map as .svg or in any other format that I can edit in escher later ?

**Comment by zakandrewking** [comment]
This is a known issue with Safari. One options is to use a different browser (Chrome and Firefox should both work).

In Safari, you can try choosing File>Save As... (or Command-S) when the page source appears. Then, in the dropdown near the bottom, switch to Page Source (rather than web archive), and name your file map.json or map.svg, etc.

Let me know if that works for you.

**Comment by zakandrewking** [comment]
- [ ] add the previous description to the Escher docs

**Comment by alyamahmoud** [comment]
Hi Zachary

unfortunately, it doesn't work. Attached is a screen shot for the error when I try to save the page source as .svg. 

So I have to re-draw the map in a different browser ? 

<img width="1041" alt="screen shot 2015-12-02 at 12 10 56 am" src="https://cloud.githubusercontent.com/assets/5653544/11514403/5e720148-9889-11e5-825a-b2cb82cb29c5.png">

**Comment by alyamahmoud** [comment]
I exported the map from the drop down menu of escher (map > export as svg) and then saved the page source as .svg. this works well. 

thanks a lot

**Comment by alyamahmoud** [comment]
same for the .json file. from the drop down menu of escher Map > export as .json > save page source as .json > reload in escher.
