### ISSUE TITLE
save image in python

### ISSUE THREAD

**Issue by zakandrewking** [zakandrewking/escher#155]
- Add 'save as image' function to ipython escher like 'save as svg' on escher.github.io

**Comment by Pathaked** [comment]
Hi!
I have been going through the codebase and wanted to work on this. Can you guide me through some pointers on how to proceed?

**Comment by zakandrewking** [comment]
Sure. Since Escher runs all on the client browser, I was looking for some ideas on converting SVG->PNG in the browser. Here is a SO thread:

http://stackoverflow.com/questions/3975499/convert-svg-to-image-jpeg-png-etc-in-the-browser

This method looks especially interesting, as long as newer browsers support it (see section SVG to Canvas):

http://svgopen.org/2010/papers/62-From_SVG_to_Canvas_and_Back/

**Comment by Pathaked** [comment]
But you mentioned before that you wanted this function in ipython esher?

**Comment by zakandrewking** [comment]
Ah yeah, you're right. I was getting off track. There are two features here that would be of interest:

1. Add the "Save SVG" function to Jupyter Escher (The original goal of this issue)
2. Add a "Save PNG" function to the Escher web application (My diversion above)

Both are interesting and useful.

Some comments on feature (1): Anything in the Jupyter notebook is divided into Python code and JavaScript code, and the data flow between them is pretty limited. The SVG image would be available to the JavaScript code because that has access to the DOM. (Python is running in a kernel behind a Jupyter server). Therefore, the easiest way to do this is to add a new UI button to the embedded JavaScript for downloading SVG, and this button would call the existing escher function `save_svg()`:

https://github.com/zakandrewking/escher/blob/master/js/src/Map.js#L2137
