### ISSUE TITLE
Jupyter integration

### ISSUE THREAD

**Issue by joaocardoso** [zakandrewking/escher#162]
@zakandrewking: the integration with jupyter seems to be broken. The javascript is trimmed (see attached figure) and the browser does not parse it.
![screen shot 2016-05-17 at 13 26 07](https://cloud.githubusercontent.com/assets/648754/15320833/f77770c6-1c32-11e6-934d-3b3b9d81de59.png)

**Comment by zakandrewking** [comment]
The JavaScript is often truncated like that in Dev Tools, but that does not
necessarily cause a problem. Can you give me more information about your
setup? Browser, Escher version, Jupyter version.

-zak

**Comment by joaocardoso** [comment]
I though so too. But I checked on google chrome to make sure it was the Devtools and I got a message "illegal character '...'".

On safari I get a JavaScript error: premature EOF

I am wondering why is it trimmed. I tried to retrieve the text in the script tag using the command line and it is incomplete.

Can it have something to do with the ipywidgets? I'll send you the versions of my deps tomorrow morning.

**Comment by joaocardoso** [comment]
Python environment: 
Python 3.4.2
Escher (1.4.0)
jupyter (1.0.0)
ipython (4.2.0)
ipywidgets (5.0.0)
Browser:
Safari Version 8.0.8 (10600.8.9)

**Comment by zakandrewking** [comment]
Thanks. I'll be out till the 24th, so I'll have to look into it next week. 






On Wed, May 18, 2016 at 1:03 AM -0700, "João Gonçalo Rocha Cardoso" <notifications@github.com> wrote:












Python environment: 

Python 3.4.2

Escher (1.4.0)

jupyter (1.0.0)

ipython (4.2.0)

ipywidgets (5.0.0)

Browser:

Safari Version 8.0.8 (10600.8.9)

**Comment by zakandrewking** [comment]
Can you check if 1.4.4 fixed this issue also?

**Comment by joaocardoso** [comment]
Hi @zakandrewking 
Still not working.

This is the part of the script you changed:

<code>

       if (typeof define === 'function' && define.amd) {
           // require.js is available: use it to load d3 and escher
           require.config({
             paths: {
               d3: '//cdnjs.cloudflare.com/ajax/libs/d3/3.5.14/d3.min',
               escher: '//npmcdn.com/escher-vis@1.4.4/js/dist/escher.min',
             },
             // Override urlArgs that adds ?v= to the end of the escher URL and
             // messes up npmcdn links. Honestly, I'm not sure if this will lead
             // to downstream bugs in the notebook, but they really shouldn't be
             // doing this cache-busting anyway.
             urlArgs: null,
           })
           require(['d3', 'escher'], function(d3, escher) {
               draw_escher(d3, escher);
           })
       } else {
           // require.js not available: dynamically load d3 & escher
           check_global_and_load('d3', '//cdnjs.cloudflare.com/ajax/libs/d3/3.5.14/d3.min.js', function(d3) {
               check_global_and_load('escher', '//npmcdn.com/escher-vis@1.4.4/js/dist/escher.min.js', function(escher) {
                   draw_escher(d3, escher);
               })
           });
       }
</code>

And I still get this: **"Failed to load resource: the server responded with a status of 403 (Forbidden)"** <span/>  https://npmcdn.com/escher-vis@1.4.0/js/dist/escher.min.js?v=20160517130948

**Comment by zakandrewking** [comment]
Have you tried it in a brand new notebook? After upgrading Escher, cached versions of things can stick around in existing notebooks. You can also try clearing all cells, saving, then refreshing.  






On Thu, May 26, 2016 at 3:42 AM -0700, "João Gonçalo Rocha Cardoso" <notifications@github.com> wrote:












Hi @zakandrewking 

Still not working.



This is the part of the script you changed:





   if (typeof define === 'function' && define.amd) {
       // require.js is available: use it to load d3 and escher
       require.config({
         paths: {
           d3: '//cdnjs.cloudflare.com/ajax/libs/d3/3.5.14/d3.min',
           escher: '//npmcdn.com/escher-vis@1.4.4/js/dist/escher.min',
         },
         // Override urlArgs that adds ?v= to the end of the escher URL and
         // messes up npmcdn links. Honestly, I'm not sure if this will lead
         // to downstream bugs in the notebook, but they really shouldn't be
         // doing this cache-busting anyway.
         urlArgs: null,
       })
       require(['d3', 'escher'], function(d3, escher) {
           draw_escher(d3, escher);
       })
   } else {
       // require.js not available: dynamically load d3 & escher
       check_global_and_load('d3', '//cdnjs.cloudflare.com/ajax/libs/d3/3.5.14/d3.min.js', function(d3) {
           check_global_and_load('escher', '//npmcdn.com/escher-vis@1.4.4/js/dist/escher.min.js', function(escher) {
               draw_escher(d3, escher);
           })
       });
   }








And I still get this: "Failed to load resource: the server responded with a status of 403 (Forbidden)"   https://npmcdn.com/escher-vis@1.4.0/js/dist/escher.min.js?v=20160517130948

**Comment by joaocardoso** [comment]
Ok, I tried in a brand new and it works. Thanks for fixing it. Cheers

**Comment by zakandrewking** [comment]
Excellent 






On Thu, May 26, 2016 at 7:01 AM -0700, "João Gonçalo Rocha Cardoso" <notifications@github.com> wrote:












Ok, I tried in a brand new and it works. Thanks for fixing it. Cheers
