### ISSUE TITLE
Naive Layout for quick viewing of SBML model without map? feature request

### ISSUE THREAD

**Issue by kastman** [zakandrewking/escher#174]
Hi all,

I have a bunch of genome-scale models from [ModelSEED](modelseed.org), and I'd love to take a look at them (they're good on building the model, but the site is still under development for visualization and model comparison). I have the models downloaded as SBML, but they don't have any associated layout (no sbml layout extension).

I know that there are several naive layout schemes for graphs (e.g. spring-loading out of d3.js which escher is using already); how much work would it be to initialize a layout with one of them just to get a brief visualization of what's inside? I know this is probably low on the priority list, and maybe another SBML visualization tool is more appropriate, but I just thought I'd mention it. 

Thanks for the great work; it looks like Escher is powerful and I hope to get back to it.

**Comment by zakandrewking** [comment]
Hi!

Automated layout (that's the term I've been using for what you describe, although I'm not sure how precise it is) has been brought up a lot, and I'm definitely interested. It is on our [wishlist](https://github.com/zakandrewking/escher/wiki/Development-Roadmap).

There is nothing stopping someone from implementing an automated layout in Escher; just time investment. If you (or anyone else) is interested in trying that out, we should talk more about the specifics of extending Escher. It should be very doable, and Escher uses D3.js which already includes methods for calculating layouts.

In the meantime, I am going to close this issue. Feel free to add ideas to that wishlist, or add new issues as you have more thoughts.

best,

zak
