### ISSUE TITLE
How to provide $

### ISSUE THREAD

**Issue by fodma1** [zakandrewking/escher#180]
I'm trying to add escher to my Angular-cli managed app. When I try to instantiate the `Builder` class, it complains about a missing reference to `$`. I saw that `$` is not required in that file, instead `/* global $ */` marks it global. How can I provide it with angular-cli / webpack?

**Comment by zakandrewking** [comment]
You will need to make sure jQuery is available globally in the app.

Alternatively, you can use the option menu='zoom' to activate a simplified
version that does not require jQuery.

We do have plans to eventually remove the jQuery dependency.

**Comment by fodma1** [comment]
Thanks for the quick reply. After a long research, I managed to figure it out. I know it does not relate strictly to the project, but I leave a [link](https://www.gurustop.net/blog/2016/11/18/3821/jquery-angular2-angularcli-how-to)  here for the record.

Can I ask what's the motivation behind expecting jquery globally? Is it something like a best practice?

**Comment by zakandrewking** [comment]
Not a best practice; just a relic of the history of the project
