### ISSUE TITLE
Tooltip tutorial documentation seems incomplete

### ISSUE THREAD

**Issue by pcm32** [zakandrewking/escher#181]
Hi there! thanks for this excellent tool @zakandrewking. I was trying to follow the tooltip tutorial at http://escher.readthedocs.io/en/latest/development-tutorial.html#getting-ready-to-develop-with-escher, however I don't get the initial intended output when lifting the web server. In the documentation, is not clear to me where is the directory where the line:

```
# python 2
python -c "import SimpleHTTPServer; m = SimpleHTTPServer.SimpleHTTPRequestHandler.extensions_map; m[''] = 'text/plain'; m.update(dict([(k, v + ';charset=UTF-8') for k, v in m.items()])); SimpleHTTPServer.test();"
```

should be invoked (as part of point 7.1). I'm presuming it would be the root directory of the git clone result, but I don't seem to get the expected result after lifting the web server, but only a directory listing. I don't seem to find anywhere either the mentioned `embedded_map_builder/index.html`.

Please let me know though if the tooltip tutorial is not where I should be looking, or why I don't see the `embedded_map_builder...` content.

Thanks!

**Comment by zakandrewking** [comment]
The server should be run in the top directory of escher-demo. The `embedded_map_builder/index.html` can be found here:

https://github.com/escher/escher-demo/blob/gh-pages/embedded_map_builder/index.html

Do you see [all these files](https://github.com/escher/escher-demo) from escher-demo in your cloned version?

**Comment by pcm32** [comment]
Thanks @zakandrewking I thought that documentation was referring to `zakandrewking/escher`, I wasn't aware of `escher/escher-demo`, maybe I failed to see this somewhere. Using the latter works like a charm!
