### ISSUE TITLE
Using Escher to visualize flux data in the context of a running Galaxy instance

### ISSUE THREAD

**Issue by pcm32** [zakandrewking/escher#182]
Hi there! I'm interested in using Escher to visualize some flux data that we generate from some tools in Galaxy (basically, an SBML with some annotations for flux values). From the Galaxy side we would like to get a folder where a static site is left, so that it only requires .js dependencies (so nothing that needs to be installed on the Galaxy instance). 

To outline what I want to do:

- Run external tool to generate SBML with fluxes annotations (SBML contains a confidence interval per flux).
- Previously generate a layout for that SBML on another Escher web process.
- Grab the SBML file with fluxes annotation with cobrapy and escher python libs to generate the json file with flux data for Escher (this runs in a container, with cobrapy, escher and all deps). 
- Create static website on a folder, where the fluxes json data is left and the layout data is left, so that the static website (which should only have .js dependencies that can be fetched by the browser) presents this data to the user within Galaxy.

Would the static website functionality cater for what I'm after? Otherwise I would need to generate an SVG or PNG from python/js automatically. Could you advice what would be the best way to proceed regarding Escher usage for what I'm after?

Thanks!
Pablo

**Comment by zakandrewking** [comment]
Hi Pablo:

The easiest way to get a static site going with Escher is to start with examples in https://github.com/escher/escher-demo. All the Escher features are available in a static site. In fact, our homepage is a static site (https://escher.github.io).

Another option is save_html in the Python API. This creates a static site on-the-fly with a given set of options:

https://escher.readthedocs.io/en/stable/python_api.html#escher.Builder.save_html
