### ISSUE TITLE
Problem in Escher E coli core map with old identifiers

### ISSUE THREAD

**Issue by alvipat** [zakandrewking/escher#185]
Hi everyone!

I'm trying to build with Escher a E coli model over the 'e_coli_core.Core metabolism'. map

However, the reaction identifiers are not matching between the model and the map. For example, for the format interchange reaction, with formula for_e -->, in my model it appears as EX_for_LPAREN_e_RPAREN_, but in the 'e_coli_core.Core metabolism' Escher map appears as EX_for_e. This makes the reaction is not found and then is not showed. This behaviour is not only for this reaction. It's also produced in other reactions.

According to BIGG, the ID, for example, EX_for_LPAREN_e_RPAREN_ is deprecated, and now it's better to use EX_for_e. The same with FORt2pp (instead FORt2) or FORtppi (now FORti)...

Nevertheless, I don't have this problem if I change the 'e coli core map' to 'e coli central metabolism'.

Exists a E coli Core map with the old identifiers? I didn't find any old version...
Or the only solution is to delete and add the reactions over tthe existen core map, or change the names over my model? 

Thank you for your time and support

**Comment by zakandrewking** [comment]
Hi @alvipat 

I would suggest changing the names over in your model. We provide a version of the e_coli_core model with new identifiers here:

http://bigg.ucsd.edu/models/e_coli_core

The downloads for that model also include notes with the original BiGG IDs to help map between them. Hope that helps!

zak
