### ISSUE TITLE
0 layouts found

### ISSUE THREAD

**Issue by anusurendra** [zakandrewking/escher#193]
Hi, 
I am trying to convert an xml smbl map file to JSON using EscherConverter. However, I am getting the foloowing error `SBML layout extension: 0 layouts found `. In addition, when I run Escher through the command line `java -jar EscherConverter-1.2.0.jar --input 166488S.xml --output ./
`, I get the following error `de.zbit.io.fileformat.FormatIdentification init --- WARNING: Could not load format identification magic byte file`

I am not sure what this error means and any advice would be much appreciated. 

Thanks in advance

**Comment by zakandrewking** [comment]
@draeger Do you have an idea on this?

It might be worth moving the issue over to EscherConverter.

**Comment by anusurendra** [comment]
Zak, 

Thank you every mush for addressing this question. I have another question, that might be related to the above. When I am developing using the escher.js and builder.css. I get the following error: `escher.js:5112 Uncaught TypeError: Cannot read property 'canvas' of undefined
    at Function.from_data (escher.js:5112)
    at constructor.load_map (escher.js:1806)
    at constructor.init (escher.js:1723)
    at constructor (escher.js:12115)
    at Object.constructor [as Builder] (escher.js:12119)
    at (index):50
    at Object.<anonymous> (d3.min.js:1)
    at Object.t (d3.min.js:1)
    at XMLHttpRequest.u (d3.min.js:1)`

Thanks again

**Comment by draeger** [comment]
@anusurendra: the missing magic byte information is nothing serious, here "warning" really means just notification of an inconvenience or suboptimal state, but not a severe problem. The real problem you are facing is that the SBML file you are trying to convert to Escher does not have any layout information. What you would need to do is to create a layout first, because EscherConverter doesn't have the ability to automatically arrange model components. Alternatively, you could parse the model with COBRApy and create a JSON model file that you can then directly load into Escher as a model. I hope this helps!

**Comment by anusurendra** [comment]
Zak,
Thanks again for you help with this. The following is the COBRAPy code I used to parse and create the JSON model file. However I still have the same problem:

```
import cobra
import os
from os.path import join

data_dir = "/home/anu/Documents/sbml_convert/"
sbmlFile = "166488.xml"

mySBML = cobra.io.read_sbml_model(join(data_dir, sbmlFile))
cobra.io.save_json_model(mySBML,join("/home/anu/Downloads/sbml/", "test.json"),pretty=True)
```
I am not sure where I made a mistake on the conversion.

Thanks again

**Comment by zakandrewking** [comment]
Hi, it looks like the issue might be that you are trying to load a model with the Load Map button (or function). There's a description of this distinction between maps and models in the docs here: 

https://escher.readthedocs.io/en/stable/escher_and_cobrapy.html

Let me know if that helps.

**Comment by anusurendra** [comment]
@zakandrewking: Thanks again. This is my JavaScript to load the model on my Escher server: 
```

<html>
  <!-- Bootstrap dependencies for the menu and buttons -->
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"/></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootswatch/3.3.5/simplex/bootstrap.min.css"/>

  <!-- d3 -->
  <script src="//cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js"></script>

  <!-- Escher files -->
  <script src="escher.js" charset="utf-8"></script>
  <link rel="stylesheet" href="builder.css"/>

  <meta charset="utf-8"/>
  <body>
    <div id="model_container"></div>

    <script>
     d3.json('166488.json', function(error, data) {
       if (error) console.warn(error);
       var options = { menu: 'all', fill_screen: true };
       var b = escher.Builder(null, data, null, d3.select('#model_container'), options);
     });
    </script>
  </body>
</html>
```

However, I now get a blank screen and the same error as before.

Thanks

**Comment by zakandrewking** [comment]
This code looks right to me. Can you double check that the error is the same one as before? It will help to see the exact error traceback. 

If you can share 166488.json, I can also try it here.

**Comment by anusurendra** [comment]
@zakandrewking Attached is the JSON file.
[166488.json.zip](https://github.com/zakandrewking/escher/files/1231816/166488.json.zip)

I am refreshed the server page and am just seeing just a blank page, with the menu options.

Thanks

**Comment by zakandrewking** [comment]
Can you try to draw a reaction? Click the *Edit > Add reaction mode* then
click anywhere on the Escher canvas. Let me know if you see any errors pop
up.

**Comment by anusurendra** [comment]
@zakandrewking 
When I do that I do not get any errors. I am able to add reactions. I had to restart my Escher server. Thanks again I really appreciate all of your help.

**Comment by zakandrewking** [comment]
Glad to hear it. Let me know if anything else comes up

zak
