### ISSUE TITLE
Does Escher work for non-model species like marine sponges?

### ISSUE THREAD

**Issue by yoyohashao** [zakandrewking/escher#196]
I have some annotated (GO, KEGG) RNA-Seq data of marine sponges. Can I use escher for pathway visualisation? Thanks

**Comment by zakandrewking** [comment]
Unfortunately, we do not have an easy way to enable this right now.

Escher relies on genome-scale metabolic models as the source of reactions and metabolites. So the first step to using Escher is to build (or download) a genome-scale metabolic model.

There are systems that quickly generate such a model for any genome (e.g. [Model SEED](http://modelseed.org/genomes/)). Once you have a model in SBML format, then I can provide guidance on converting the model to the format required by Escher.

Thanks for sharing your use case. We are always interested to hear how people might use Escher as we develop future versions.

zak
