### ISSUE TITLE
Improve Doc: options.zoom_to_element takes 'reaction' or 'node' as type

### ISSUE THREAD

**Issue by yugi03** [zakandrewking/escher#199]
Hi There,

I am using javascript api for building escher maps. I was interested to zoom to a particular metabolite when the map loads. In your documentation it is mentioned that 

> _options.zoom_to_element_

 takes type as either 'reaction' or 'metabolite' which is incorrect. But to zoom to a particular metabolite, type should be given as 'node'. Please improve the documentation.
The link is [here](http://escher.readthedocs.io/en/stable/javascript_api.html#options.zoom_to_element)

**Comment by zakandrewking** [comment]
Thanks for reporting this! We will absolutely fix for the next release.

**Comment by yugi03** [comment]
Hey, I raised a PR for the same.
