### ISSUE TITLE
Accessing a reaction's definition of primary and secondary metabolites

### ISSUE THREAD

**Issue by Midnighter** [zakandrewking/escher#206]
Hey,

@matyasfodor is working on a feature to implement automatic addition (rendering) of reactions to an existing map. In most cases we would like to add new reactions to existing primary metabolites (if possible). As far as I understand from Matyas Escher has a global list of co-factors but clearly each reaction also defines its primary metabolite. Is that information accessible somehow?

**Comment by zakandrewking** [comment]
It's easy to find in a downloaded map JSON file. Each node has a `node_is_primary` attribute.

Do you mean you want to access it from a running instance of Escher? If so, check out:

```
builder.map.nodes[node_id].node_is_primary
```

Let me know if you need further info.

**Comment by Midnighter** [comment]
I misunderstood the problem a bit. All good :smile:
