### ISSUE TITLE
Send a vector of reaction ids to Escher to draw

### ISSUE THREAD

**Issue by anusurendra** [zakandrewking/escher#216]
Hi,

I am wondering if there is a way to send Escher a vector of reaction ids from the loaded model and the map is drawn based on these ids?

Thanks,
Anu

**Comment by zakandrewking** [comment]
This can be done with some JavaScript code. There's an example here:

https://github.com/escher/escher-test/blob/master/src/reaction_shapes.js

Here it is running:

http://zak.ucsd.edu:7622

This requires some code to choose where to draw reactions and what angles to draw them at, but you could play around with it. Let me know if I can provide more details.

**Comment by anusurendra** [comment]
Zak,
Thanks for the prompt. So, I am trying to incorporate the code into my solution. However, I am having a problem. From my understanding the code that is relevant to me is the this:
  ```
const draw = (bigg_id, loc, rot) => {
    this.map.new_reaction_from_scratch(bigg_id, loc, rot)
    this.map.new_reaction_for_metabolite(
      bigg_id, Object.keys(this.map.get_selected_nodes())[0], rot
    )
  }
```

Below, is the code (on a separate JS file) for my test function:
```
import { Builder } from 'escher-vis';
import * as d3 from 'd3';

import 'builder.css';

function myFunction(){
  const draw = (bigg_id, loc, rot) => {
    d3.select('#model_container').map.new_reaction_from_scratch(bigg_id, loc, rot)
    d3.select('#model_container').map.new_reaction_for_metabolite(
      bigg_id, Object.keys(d3.select('#model_container').map.get_selected_nodes())[0], rot
    )
  };
}

```

However, I am getting a function cannot be found error from my JS.

Thanks again,
Anu Surendra

**Comment by zakandrewking** [comment]
Ah, `d3.select('#model_container')` has a `map` attribute, but it's not an Escher object. It's just the [built-in `map` function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map). A little confusing.

You need to keep a reference to the Escher Builder object, so you can call:

```
builder.map.new_reaction_from_scratch(bigg_id, loc, rot)
```

**Comment by anusurendra** [comment]
Zak,

Is this the way to get the Escher Builder object:
 `var b = escher.Builder(null, data, null, d3.select('#model_container'), options);`

There for the above code would be:
`b.new_reaction_from_scratch(bigg_id, loc, rot)`

Also, how do I save an updated version of the drawn map using the Escher Builder?

Again, I really appreciate your patience and help,

Thanks,
Anu Surendra

**Comment by zakandrewking** [comment]
Looks good to me

If you want to save, you can manually click Save Map JSON on the website, or programmatically you can pull out the map with:

```
b.map.map_for_export()
```

**Comment by anusurendra** [comment]
Zak,

I have following function:
```
function loadModelDDFile(){
     var b;
     var value="e_coli_core.json";
    d3.json(value, function(error, data) {
        if (error) console.warn(error);
      var options = {menu: 'all', canvas_size_and_loc: { x: '200px', y: '200px', width: '5000px', height: '5000px' }};
      b = escher.Builder(null, data, null, d3.select('#model_container'), options);
  });
   b.new_reaction_from_scratch('acald_c',{ x: 0, y: 90 }, 90)
}
```
However, the `b.new_reaction_from_scratch('10fthf6glu_c',{ x: 0, y: 90 }, 90)` does not seem to be drawing the reaction.

Thanks,
Anu Surendra

**Comment by zakandrewking** [comment]
you will have to put `b.map.new_reaction_from_scratch ... ` inside the `d3.json` callback function

**Comment by anusurendra** [comment]
Zak,

Sorry, I tried the function with the `b.map.new_reaction_from_scratch` inside the callback function and still do not have the reaction drawn.

```
 function loadModelDDFile(){
   
     var value="e_coli_core.json";
    d3.json(value, function(error, data) {
        if (error) console.warn(error);
      var options = {menu: 'all', canvas_size_and_loc: { x: '200px', y: '200px', width: '5000px', height: '5000px' }};
     var b = escher.Builder(null, data, null, d3.select('#model_container'), options);
     b.map.new_reaction_from_scratch('acald',{ x: 0, y: 90 }, 90)
  });
}
```

Thanks again for your help and patience,
Anu Surendra

**Comment by zakandrewking** [comment]
make sure that the reaction ID you pass exists in the model. In this case, `acald_c` is not a reaction in e_coli_core. Try `ACALD`.

**Comment by anusurendra** [comment]
Zak,

I have tried  `b.map.new_reaction_from_scratch('ACALD',{ x: 0, y: 90 }, 90)` as well and the reaction is not drawn.

**Comment by zakandrewking** [comment]
you can look in the developer tools console for an error message

https://developer.chrome.com/devtools

**Comment by anusurendra** [comment]
Zak,

I have and the only errors that is being thrown is in `escher.Builder(null, data, null, d3.select('#model_container'), options);`  and `var b = escher.Builder(null, data, null, d3.select('#model_container'), options);`. But I believe that these errors are thrown due to the map parameter being null and . Attached a screenshot of the console 
![screenshot from 2017-11-17 14-17-46](https://user-images.githubusercontent.com/5685804/32965414-63b56f00-cba4-11e7-9598-95820730ceeb.png).

![screenshot from 2017-11-17 14-41-35](https://user-images.githubusercontent.com/5685804/32965933-3854ea78-cba6-11e7-931d-074bf696299b.png)

**Comment by anusurendra** [comment]
Zak,

I was able to figure out the issue. For the option `canvas_size_and_loc: { x: '200', y: '200', width: '5000', height: '5000' }` I had added 'px' to the x,y, width and height values. Sometimes, it is the silliest errors :).

Is there a way to clear the map programmatically?

Thanks again for your help and patience,
Anu Surendra

**Comment by zakandrewking** [comment]
`builder.map.clear_map()` :)

**Comment by anusurendra** [comment]
Zak,
Thanks for that. One other quick question, I am trying to get the coordinates of the selected nodes and here is the code I have:

```
b.map.select_all();
   var sn = b.map.get_selected_nodes();

   for (p in sn) {
      var co = b.map.get_coords_for_node(p);
    }

```
However, I am getting an error on `b.map.get_coords_for_node(p)`. I looked at the function and the only parameter it needs is the node_id, which is `p`.

Thanks again,
Anu Surendra

**Comment by zakandrewking** [comment]
try `get_selected_node_ids` instead of `get_selected_node`

**Comment by anusurendra** [comment]
@zakandrewking,

Is there a way to invoke the "Add reaction mode" programmatically?
