### ISSUE TITLE
Possible to enable "gene scale" and how to use "reaction_scale" correctly via Python API?

### ISSUE THREAD

**Issue by willigott** [zakandrewking/escher#221]
I currently display a map as follows:

```
temp_json = Builder(map_json=template_map_path, model_json=json_mod, highlight_missing=True, 
                    gene_data=data_dict)

temp_json.display_in_browser(scroll_behavior='zoom')
```
My question is whether there is a way to control the scaling for the gene data. If e.g. I have three time points, `A`, `B` and `C` and display the differences between `A` and `B` and `A` and `C`, then the same color might be used for a very different number which makes comparison difficult. I saw that there is `reaction_scale` and  `metabolite_scale` available but did not see anything for genes. Is it available and if so, how can I call it?

Related to this:
What should be passed to `reaction_scale`? I tried passing a list of three floats representing the minimum, median and maximum used in the color map. This does not throw an error but does not show anything either (gives just a white screen). How would it be done correctly and how can one set these three values from a Python script?

**Comment by zakandrewking** [comment]
gene data also respects `reaction_scale`

There is an example of `reaction_scale` in the JavaScript docs here:

https://escher.readthedocs.io/en/stable/javascript_api.html#options.reaction_scale

It works the same way for Python.

**Comment by willigott** [comment]
Thanks a lot for the link.
