### ISSUE TITLE
 Programmatically draw a reaction

### ISSUE THREAD

**Issue by anusurendra** [zakandrewking/escher#227]
Hi @zakandrewking ,
Is there a way to programmatically draw a reaction to a selected node?  I am trying to invoke the reaction creation dropdown with a selected reaction onto a selected node.

**Comment by zakandrewking** [comment]
Can you clarify what you mean? The only programatic drawing APIs we have now are the undocumented ones discussed earlier https://github.com/zakandrewking/escher/issues/216

**Comment by anusurendra** [comment]
@zakandrewking,

Thanks for the reply. I am wondering if there is a way to invoke the 'reaction' creation button and invoke the reaction dropdown with the passed metabolite and coordinates.

**Comment by zakandrewking** [comment]
No, this is not currently possible.

However, if you can describe you use case, we might be able to help you in
a future Escher version.

**Comment by anusurendra** [comment]
@zakandrewking,
So, I have created a sidebar to my Escher page, which will provide the dropdowns for all the metabolites, the associated reactions for a selected model. When the user selects the reaction, it is drawn on the map.

**Comment by zakandrewking** [comment]
Got it. Thanks! I'm going to close this issue, but we'll keep that in mind.
