### ISSUE TITLE
Builder fails if JSON file uses indentation

### ISSUE THREAD

**Issue by willigott** [zakandrewking/escher#229]
When I use cobrapy's `.io.to_json` function with `indent=4` and pass this to the Escher builder, it fails to load the model; the code below reproduces the problem:

```
import cobra
from escher import Builder

model = cobra.io.read_sbml_model('e_coli_core.xml')

# # This works
# json_repr = cobra.io.to_json(model)

# This does not work
json_repr = cobra.io.to_json(model, indent=4)

b = Builder(model_json=json_repr)
b.display_in_browser(scroll_behavior='zoom')
```

Clearly, this is just cosmetics but I usually prefer to save models using indentation as they are then still readable. Is there any specific reason for the above's behavior?

**Comment by zakandrewking** [comment]
I agree we should fix this. thanks for the clear report.
