### ISSUE TITLE
Path of js and css files are not found (broken link on doc)

### ISSUE THREAD

**Issue by yugi03** [zakandrewking/escher#248]
Hi @zakandrewking 

I am using escher library for past 4 months. I used the link provided in the doc to add escher in my project. Link for them was as shown below:

<script src="https://unpkg.com/escher-vis/js/dist/escher.min.js"></script>
<link href="https://unpkg.com/escher-vis/css/dist/builder.min.css" rel="stylesheet">

Suddenly, I realised that my app is breaking in `prod` and after little debugging, I found out that above links are not found.

Can you let me know some other stable link, which I can use for my app.

Thanks

**Comment by zakandrewking** [comment]
Yes, sorry about that. We are in the processing of moving from `escher-vis` to `escher`, and i accidentally broke backwards-compatibility there. Fixed now.

**Comment by zakandrewking** [comment]
To be safe, I recommend using the form that specifies the version, e.g.:

https://unpkg.com/escher-vis@1.6.0/js/dist/escher.min.js

For the next release, it will be:

https://unpkg.com/escher@1.7.0/js/dist/escher.min.js

**Comment by yugi03** [comment]
Thanks @zakandrewking . For now, I am using `1.6.0` version. Will move to `1.7.0` when it will be released.
