### ISSUE TITLE
Color picker isn't working in scale editor

### ISSUE THREAD

**Issue by zakandrewking** [zakandrewking/escher#249]
Error: 

![screen shot 2018-02-08 at 4 05 19 pm](https://user-images.githubusercontent.com/1250400/36004911-f101600e-0ce9-11e8-8e6a-3cb222b8b300.png)

**Comment by zakandrewking** [comment]
@spaghettikinase have you seen this before?

**Comment by spaghettikinase** [comment]
Fixed. Opened a pull request.
