### ISSUE TITLE
How to create a pathway knockout ?

### ISSUE THREAD

**Issue by LeducH** [zakandrewking/escher#255]
I checked to documentation and was wondering how I can create my own knockout map with Escher. I used  [this](https://escher.github.io/escher-demo/knockout/)  as example and I tried to understand the code. 

Since I am missing the part how the javascript handles the click events so that the color changes   and show when E coli is killed when enough reactions are knocked out. 

It would be great if there would be a small example with 4-5 reactions explaining how to handle the click events and show a custom message when the organism is killed.

**Comment by zakandrewking** [comment]
Let's continue discussing in the issue you reported on escher-demo
