### ISSUE TITLE
Map does not contain 3ohodcoa_c

### ISSUE THREAD

**Issue by zakandrewking** [zakandrewking/escher#262]
Escher Map does not contain 3ohodcoa_c, instead it contains 3oodcoa_c

happens here http://bigg.ucsd.edu/models/iJO1366/reactions/ACACT8r
and http://bigg.ucsd.edu/models/iJO1366/reactions/HACD8

thanks @jlerman44 for reporting. moved from SBRG/bigg_models#284

**Comment by elliotgordonrowe** [comment]
Is this a bug with Escher? It looks like the map wasn't made right or something.
