### ISSUE TITLE
feature request: Autocomplete for search bar

### ISSUE THREAD

**Issue by elliotgordonrowe** [zakandrewking/escher#263]
Had a request for the search bar to display the top ten hits instead of requiring the users to cycle through each individual hit.

**Comment by zakandrewking** [comment]
Do you mean an autocomplete search box (like what we have on the bigg homepage)?

Or do you mean showing all results for a given search term (like what google maps does)?

**Comment by elliotgordonrowe** [comment]
I think an autocomplete search box would work best. Maps might be too big to differentiate different points for large numbers of hits.

**Comment by zakandrewking** [comment]
cool
