### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by projazz** [zakandrewking/escher#276]
I'm getting super slow page loading throughout Escher Interactive.  Ultimately icons do not load and all interactive maps lead to a 502 Bad Gateway Error.  I'm specifically interested in access to iAB-RBC-283.  Months ago the site worked perfectly.  Is Escher Interactive no longer being developed?

**Comment by jtyurkovich** [comment]
Thanks for pointing this error out -- I will look into it. Hopefully the server just needs a reboot.

We do not actively develop Escher Interactive at present. However, if you are specifically interested in the red blood cell, then I would direct you to our latest project, [ErythroDB](www.erythrodb.org). ErythoDB is built from Escher Interactive but is an RBC specific knowledgebase. It has additional features like a searchable Bibliome and Data Repository for RBC data sets beyond just the Map (although the Map has several additional features beyond those provided by Escher Interactive).
