### ISSUE TITLE
Features for a functional builder

### ISSUE THREAD

**Issue by zakandrewking** [zakandrewking/escher#28]
Goal:  Build the _E. coli_ core metabolic map in < 10 minutes.

- [x] Change the direction of a new reaction before adding it. (Arrow next to metabolite can be dragged to determine direction)
- [x] Undo with Ctrl-Z
- [x] Combine metabolites from different reactions
- [x] Export as SVG
- [x] Drag bezier points
- [ ] Add new control points
- [x] Change the size of the map border
- [ ] Add membranes
- [x] Show main products of a reaction (as a hint) in reaction input menu
- [ ] Smart bezier displacement when a node gets dragged
- [x] Show flux on builder reactions
- [ ] Snap to grid
- [x] Directional arrows to show (a) reversibility and (b) flux direction
- [x] Drag metabolite and reaction labels
- [x] Add new text labels

Anything else? @jlerman44?

**Comment by abulovic** [comment]
Maybe it is a superfluous question, but how can I combine the nodes from the web interface?
