### ISSUE TITLE
SVG exporting exports GUI elements too

### ISSUE THREAD

**Issue by cladelpino** [zakandrewking/escher#280]
Hi, not a big issue for me because I can just edit the exported svg, but it also looks as an easy to fix one, so I thought I might report it. 

When exporting to SVG,  "control points", the "rotate" tool cross , the "add reaction" arrow, etc also get exported. 

I am opening the SVG with inkscape 0.92.3

**Comment by zakandrewking** [comment]
Thanks for the report. I'll see if I can recreate it.

**Comment by zakandrewking** [comment]
Confirmed: Also happens on macOS 10.13.6 with Inkscape 0.92.2 (but not with Illustrator CC).

**Comment by zakandrewking** [comment]
fixed now!

https://escher.github.io
