### ISSUE TITLE
Allowing a self defined color scale

### ISSUE THREAD

**Issue by Midnighter** [zakandrewking/escher#281]
I'd love to be able to pass my own defined color scale into Escher. There are two reasons:

1. At the moment escher splits a data distribution into desired quantiles (or similar) every time a new distribution is drawn but I'd like to use the same consistent scale across many different data sets.
2. I would love to have full control over colors being drawn at certain exact values and intervals.

**Comment by zakandrewking** [comment]
Just to restate the options from our discussion @ COBRA:

a) provide an API so a user can provide a function that will determine the color based on data (probably via d3.scale so it's friendly to a scale bar implementation)

b) after #242, color scales will normalize the data scale across any number of loaded datasets. this might do the trick for simple cases

**Comment by zakandrewking** [comment]
just following up on this

now our color scales do not require a min and max, so you can fully control them with values. does this get you what you need?

new beta release is available now on NPM and the website

**Comment by zakandrewking** [comment]
The docs are up-to-date here: https://escher.readthedocs.io/en/latest/javascript_api.html#escher.Builder.options.reaction_scale

But it's the same kind of scale as before. We just removed the requirement that you include a `max` and `min` in the scale. That way, you can create a nice, consistent scale that survives changes in data.

The Python package isn't ready. You could try installing it from source, but it will be missing some features.

**Comment by Midnighter** [comment]
Does you closing this issue mean that it's also accessible via the Python package now?

**Comment by zakandrewking** [comment]
Yup! `pip install -U --pre escher`
