### ISSUE TITLE
Loss of arrows after convertion

### ISSUE THREAD

**Issue by anusurendra** [zakandrewking/escher#283]
I used KeggTranslator to convert a KGML file to SBML_L3V1. Then am using the EscherConverter to convert it to JSON map file to put into Escher. However, when I load the converted map to Escher, the arrows and connectors (ie the reaction direction) are gone:

![image](https://user-images.githubusercontent.com/5685804/51054612-69323600-15ab-11e9-895d-04b3fabfb29c.png)

I am attaching the converted files:
[hsa00630.sbml.zip](https://github.com/zakandrewking/escher/files/2750869/hsa00630.sbml.zip)
[hsa00630.json.zip](https://github.com/zakandrewking/escher/files/2750877/hsa00630.json.zip)

Any help is much appreciated.

**Comment by zakandrewking** [comment]
closing in favor of https://github.com/draeger-lab/EscherConverter/issues/34
