### ISSUE TITLE
Conversion between xml format and json format

### ISSUE THREAD

**Issue by hongzhonglu** [zakandrewking/escher#306]
Hi I have maps in xml format, which can be used for the cellDesigner, are there methods to change it into json format?

**Comment by zakandrewking** [comment]
You're best bet would be to convert from cell designer to SBML and then SBML to JSON. This has been done before, but I'm not sure how general the approach is. @draeger Do you have any advice?

**Comment by draeger** [comment]
Indeed. The [supplement](https://media.nature.com/original/nature-assets/nbt/journal/v36/n3/extref/nbt.4072-S3.pdf) of the [Recon 3D paper](https://dx.doi.org/10.1038/nbt.4072) describes in detail how to proceed (from page 18), including several post-processing steps. Here is only a short version:
1. You can use the [celldesigner-parser](https://github.com/funasoul/celldesigner-parser) project to convert CellDesigner models to the [SBML](http://sbml.org) format with [Layout extension](http://sbml.org/Special/specifications/sbml-level-3/version-1/layout/sbml-layout-version-1-release-1.pdf).
2. In the second step, you can load the generated file as input to [EscherConverter](https://github.com/draeger-lab/EscherConverter/) and export it to Escher's JSON format.

I hope this helps!

**Comment by hongzhonglu** [comment]
Great thanks for your help! It is very useful for me.
