### ISSUE TITLE
permission to convert and re-distribute Escher maps in Dash-Cytoscape

### ISSUE THREAD

**Issue by kozo2** [zakandrewking/escher#319]
Would it be possible to get permissin to convert and visualize (almost equal re-distribute) the Escher maps with [Dash-Cytoscape](https://dashr.plot.ly/cytoscape)?
This is related to https://github.com/SBRG/bigg_models/issues/352

**Comment by zakandrewking** [comment]
Yes, the maps are available here along with source code under the MIT license:

https://github.com/escher/escher.github.io/tree/master/1-0-0/6

If necessary, we can relicense those data files under CC0 as well

**Comment by kozo2** [comment]
Thank you for your reply. (I'm sorry for this late reply.)
For now, the MIT license is good enough.
I will contact you again when I release Escher maps derivative work.
