### ISSUE TITLE
PYK flux on core map not showing

### ISSUE THREAD

**Issue by Karrenbelt** [zakandrewking/escher#322]
Probably just a minor issue: the flux for PYK is gives 'n.d.' even though there is a flux in the csv file I'm trying to load as reaction data. I don't think the attached csv is of much help, but added for the sake of completeness. I was added .txt to be able to upload it here.

map: https://escher.github.io/#/app?map=e_coli_core.Core%20metabolism&tool=Builder&model=e_coli_core

csv: 
[pyk_no_shown_on_core_map.csv.txt](https://github.com/zakandrewking/escher/files/3743853/pyk_no_shown_on_core_map.csv.txt)

**Comment by zakandrewking** [comment]
this should be better-documented, but you need to add a header row to the CSV. e.g.

[pyk_no_shown_on_core_map.csv.txt](https://github.com/zakandrewking/escher/files/3745113/pyk_no_shown_on_core_map.csv.txt)
