### ISSUE TITLE
streamlit BIGG

### ISSUE THREAD

**Issue by ghost** [zakandrewking/escher#391]
For those who are using the python 3.12 and escher is not loading. I coded a streamlit application that will give you all the information. I am devloping a new julia based desktop application that will give you all the BIGG analyze including the metabolic modelling with in that application. 

https://github.com/gauravcodepro/streamlit-BIGG-metabolic-analyzer-API

Thank you Gaurav

**Comment by elliotfontaine** [comment]
Hi @gauravcodepro. I don't understand how that relates to escher. Did you manage to integrate the escher viewer in a Streamlit app ? That would be neat!

**Comment by ghost** [comment]
@elliotfontaine thank you and i am working on developing a desktop based application and also some more struct based approaches and that will give you a faster access to make escher maps. I shall be updating this soon. The streamlit application that i developed gives you all the information about the associated with the given metabolic model and that is what the application says. 

To make the escher maps, check out in sometime, a complete desktop application for making the escher maps that fetches the API directly from the BIGG and uses D3 javascript to make the maps. 

Thank you, Gaurav
