### ISSUE TITLE
Some bug with ctrl+z in mapbuilder

### ISSUE THREAD

**Issue by dczielinski** [zakandrewking/escher#87]
So I was trying to move a set of reactions with the selection tool. When I select something with shift+click, then move, then undo, it actually performs an additional move in the same direction again. Furthermore, when I do the shift click, it doesn't move the control points as well.

**Comment by zakandrewking** [comment]
I haven't been able to recreate this. If you see it again, come grab me.

**Comment by dczielinski** [comment]
Ugh I'm having trouble getting it to show up again..I think I already have habits that avoid it and I can't remember the exact click order - I'll let you know if I see it again.
