### ISSUE TITLE
color by absolute value

### ISSUE THREAD

**Issue by aebrahim** [zakandrewking/escher#88]
It appears that negative flux values are not being colored.
![not_coloring](https://cloud.githubusercontent.com/assets/1380168/6757532/0862b0f4-ceef-11e4-89e9-4cb98a7f07c7.png)

``` python
>>> import escher
>>> escher.__version__
'1.1.0'
```

**Comment by zakandrewking** [comment]
Have you tried the 'absolute value' setting? Are you running from the Python package?

**Comment by aebrahim** [comment]
Oh, my bad, I guess I should RTFM.

In any case, I think that coloring by absolute value might what people assume the default is.

**Comment by zakandrewking** [comment]
OK. That's not a bad idea. Thanks for putting it up here.
