### ISSUE TITLE
problem with 'version' module in latest release

### ISSUE THREAD

**Issue by jsalamos** [zakandrewking/escher#89]
In macOSX when importing escher the following error is raised:

import escher
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-6-63f9fae30b96> in <module>()
----> 1 import escher

/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Escher-1.1.0-py3.4.egg/escher/__init__.py in <module>()
----> 1 from version import __version__, __schema_version__
      2 
      3 from plots import (Builder, get_cache_dir, clear_cache, list_cached_maps,
      4                    list_cached_models, list_available_maps, list_available_models)
      5 

ImportError: No module named 'version'

**Comment by zakandrewking** [comment]
Thanks @jsalamos. Hopefully #97 solves this.
