### ISSUE TITLE
feature request: retrieve node information

### ISSUE THREAD

**Issue by dczielinski** [zakandrewking/escher#90]
In general, it seems like you can move labels around as you will, which allows you to potentially improperly label notes by getting the labels mixed up. This would prevent you from merging nodes, for example, if they got switched, or could cause incorrect stoichiometries. Double clicking on a node to display the metabolite name would be a nice feature, or tooltip-ing it would be another option (same for reactions I guess)

**Comment by dczielinski** [comment]
Actually, I've since noticed that moving the node moves the label too, so this is a nice practical solution by just watching for which label moves. Certainly enough as is to avoid any disasters, so probably not a pressing issue to change anything

**Comment by elliotgordonrowe** [comment]
@zakandrewking the moretooltips feature added the datum to be passed up upon mouseover or touch. I can add other information to the datum if anything else is needed.
