### ISSUE TITLE
Feature request: get C hotkey to work when in new reaction mode

### ISSUE THREAD

**Issue by dczielinski** [zakandrewking/escher#92]
So, right now, if you're creating a new reaction in a chain, and there's a reaction list currently up, and you hit C to get a reaction list for a different metabolite, it instead searches for "C" in the reaction list. Not sure what a good fix for this would be, maybe making alt+C work instead or something more robust like that?

**Comment by zakandrewking** [comment]
Oh, simple solution. Hit Escape then C. Let me know if that works.

**Comment by dczielinski** [comment]
Works, thanks!
