### ISSUE TITLE
Control point bugs

### ISSUE THREAD

**Issue by dczielinski** [zakandrewking/escher#93]
One common bug is when selecting a metabolite and moving it, it leaves the control point behind. Then, when you click on the control point and drag it a bit, it warps it back to the metabolite.

Leaving the control points behind also happens frequently when selecting groups of metabolites/reaction control points to move.

**Comment by dczielinski** [comment]
Ah, just found out that switching to pan mode and zooming fixes this, so that's certainly not a big issue practically

**Comment by zakandrewking** [comment]
I can't recreate this, so closing. Feel free to open the issue if you see it again.
