### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by phantomas1234** [zakandrewking/escher#94]
import escher

raises

    ---------------------------------------------------------------------------
    ImportError                               Traceback (most recent call last)
    <ipython-input-1-63f9fae30b96> in <module>()
    ----> 1 import escher

    /Users/niko/.virtualenvs/escher_py3/lib/python3.4/site-packages/escher/__init__.py in <module>()
    ----> 1 from version import __version__, __schema_version__
          2 
          3 from plots import (Builder, get_cache_dir, clear_cache, list_cached_maps,
          4                    list_cached_models, list_available_maps, list_available_models)
          5 

    ImportError: No module named 'version'

on OS X 10.10.2, escher 1.1.0 (installed via `pip install escher`) and python 3.4.3 (inside a virtualenv).

I am aware that tests run fine under 3.4 on travis (https://travis-ci.org/zakandrewking/escher/jobs/54929411) which makes this weird. Any ideas why that is?

Technically, imports like `from version import __version__, __schema_version__` shouldn't work in python3.4. I am pretty sure it has to be `from .version import __version__, __schema_version__`

**Comment by zakandrewking** [comment]
I have no idea why Travis was OK with that code, but I switched it to an absolute import. Let me know if you see anything else that Travis misses!

I'll try to release this as 1.1.1 ASAP
